# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Mythofys
tagline:          'A Jekyll theme'
description:      '가 PS하는 블로그여야 하는 것'
theme:            jekyll-theme-hydeout
url:              https://windrew.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname:      Mythofys

google_analytics: UA-100461102-1

# Used for Hydeout's own Github page. Feel free to remove for your
# own fork.
hydeout:
  version:          5.0.2
  repo:             https://github.com/windrew/windrew.github.io

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax